In [13]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.ensemble import IsolationForest

In [21]:
df = pd.read_csv("D:/Machine_Learning/Datasets/milk.csv", index_col=0)
clf = IsolationForest(contamination=0.05,random_state=26)
clf.fit(df)
predictions = clf.predict(df)
predictions

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1, -1])

In [22]:
df

            water  protein   fat  lactose   ash
Animal
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.9  2.30
RAT          72.5      9.2  12.6      3.3  1.40
DEER         65.9     10.4  19.7      2.6  1.40
REINDEER     64.8     10.7  20.3      2.5  1.40
WHALE        64.8     11.1  21.2      1.6  1.70
SEAL         46.4      9.7  42.0      0.0  0.85
DOLPHIN      44.9     10.6  34.9      0.9  0.53

In [28]:
glass = pd.read_csv("D:/Machine_Learning/Cases/Glass_Identification/Glass.csv")
glass

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe                              Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0  building_windows_float_processed
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0  building_windows_float_processed
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0  building_windows_float_processed
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0  building_windows_float_processed
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0  building_windows_float_processed
..       ...    ...   ...   ...    ...   ...   ...   ...  ...                               ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0                         headlamps
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0                         headlamps
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0                         headlamps
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0                         headlamps
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0                         headlamps

[214 rows x 10 columns]

In [29]:
# le = LabelEncoder()
# glass['Type'] = le.fit_transform(glass['Type'])
X , y = glass.drop(['Type'], axis=1), glass['Type']

In [33]:
clf = IsolationForest(contamination=0.05,random_state=26)
clf.fit(X)
predictions = clf.predict(X)
predictions

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1])

In [34]:
pd.crosstab(y, predictions, margins=True)

col_0                                 -1    1  All
Type
building_windows_float_processed       0   70   70
building_windows_non_float_processed   3   73   76
containers                             3   10   13
headlamps                              4   25   29
tableware                              1    8    9
vehicle_windows_float_processed        0   17   17
All                                   11  203  214

In [32]:
# scaler = StandardScaler()
# X_scl = scaler.fit_transform(X)
clf = IsolationForest(contamination=0.1,random_state=26)
clf.fit(X)
predictions = clf.predict(X)
pd.crosstab(y, predictions, margins=True)

col_0                                 -1    1  All
Type
building_windows_float_processed       0   70   70
building_windows_non_float_processed   8   68   76
containers                             5    8   13
headlamps                              7   22   29
tableware                              1    8    9
vehicle_windows_float_processed        1   16   17
All                                   22  192  214

## Removing Outliers

In [37]:
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV

In [38]:
# Assuming glass, predictions, LabelEncoder, and np are already defined/imported
in_glass = glass[predictions != -1]
le = LabelEncoder()
in_glass['Type'] = le.fit_transform(in_glass['Type'])
X, y = in_glass.drop('Type', axis=1), in_glass['Type']

kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=26)

params = {
    'learning_rate': np.linspace(0.0001, 0.9, 30), 
    'n_estimators': [10, 25, 50, 75, 100],
    'max_depth': [2, 3, 4, 5, 6]
}

gbm = XGBClassifier(random_state=26, n_jobs=-1)
gcv = GridSearchCV(gbm, param_grid=params, cv=kfold, scoring='neg_log_loss')

gcv.fit(X, y)
gcv.best_params_, gcv.best_score_

({'learning_rate': np.float64(0.09319310344827586),
  'max_depth': 3,
  'n_estimators': 75},
 np.float64(-0.6676643119852299))