In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import  ColumnTransformer
from sklearn.metrics import r2_score, log_loss

from sklearn.neighbors import KNeighborsRegressor

import os
os.chdir("D:/Machine_Learning/Datasets") #fetch the dataset from the folder

## Boston Data

In [88]:
boston = pd.read_csv("Boston.csv")
X = boston.drop('medv',axis=1)
y=boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [52]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

   Ks     score
3   4  0.588671
2   3  0.559148
4   5  0.556344
5   6  0.515386
1   2  0.513579
6   7  0.496433
7   8  0.491477
8   9  0.479582
9  10  0.448195
0   1  0.293025

### With Standard Sclaing

In [53]:
scaler = StandardScaler().set_output(transform="pandas")

In [54]:
scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

In [55]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

   Ks  R2 score
4   5  0.720809
3   4  0.720349
1   2  0.720333
8   9  0.708297
5   6  0.705555
2   3  0.704720
7   8  0.701514
6   7  0.701001
9  10  0.698105
0   1  0.691733

## MinMax

In [56]:
scaler = MinMaxScaler().set_output(transform="pandas")

In [57]:
scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

In [58]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

   Ks  R2 score
2   3  0.713301
3   4  0.711778
4   5  0.704968
1   2  0.692504
5   6  0.677821
0   1  0.675963
6   7  0.655112
7   8  0.639558
8   9  0.633555
9  10  0.627269

# Housing Dataset

In [59]:
housing = pd.read_csv('Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [60]:
X = housing.drop('price',axis=1)
y=housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [61]:
from sklearn.compose import make_column_selector

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")

trans = ColumnTransformer(
    transformers=[("OHE", ohe, make_column_selector(dtype_include=object))], remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [62]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred = knn.predict(X_tst_ohe)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

    Ks     score
10  11  0.400090
11  12  0.389124
12  13  0.383862
9   10  0.383108
13  14  0.379195
8    9  0.377442
7    8  0.374427
14  15  0.372651
5    6  0.371384
6    7  0.350074
4    5  0.326117
3    4  0.276338
2    3  0.211714
1    2  0.057812
0    1 -0.010284

### Standard Scale

In [69]:
scaler = StandardScaler().set_output(transform="pandas")

In [70]:
scaler.fit(X_trn_ohe)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_trn_ohe)  # Actual transformation of data
X_tst_scl = scaler.transform(X_tst_ohe)

In [71]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
9   10  0.704812
10  11  0.697848
8    9  0.692825
14  15  0.689817
6    7  0.687105
11  12  0.686939
12  13  0.686772
13  14  0.686302
7    8  0.681864
5    6  0.673463
3    4  0.669234
4    5  0.665637
2    3  0.656770
1    2  0.568237
0    1  0.470837

### MinMax Scaler

In [72]:
scaler = MinMaxScaler().set_output(transform="pandas")

In [73]:
scaler.fit(X_trn_ohe)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_trn_ohe)  # Actual transformation of data
X_tst_scl = scaler.transform(X_tst_ohe)

In [74]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
3    4  0.648484
5    6  0.634816
4    5  0.629438
2    3  0.617526
6    7  0.615586
8    9  0.613230
7    8  0.609255
9   10  0.609119
10  11  0.600157
14  15  0.587456
11  12  0.586856
13  14  0.580209
12  13  0.577529
1    2  0.525986
0    1  0.332474

# Concrete Strength

In [80]:
os.chdir("D:/Machine_Learning/Cases/Concrete_Strength")
conc = pd.read_csv("Concrete_Data.csv")
X, y = conc.drop('Strength', axis=1), conc['Strength']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26)

In [83]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
3    4  0.686443
4    5  0.677831
2    3  0.670443
5    6  0.664499
6    7  0.655339
7    8  0.654481
8    9  0.653360
9   10  0.650433
10  11  0.644905
11  12  0.638284
12  13  0.630390
13  14  0.617334
0    1  0.600760
14  15  0.597252
1    2  0.585665

In [84]:
# Standard Scaler
scaler = StandardScaler().set_output(transform="pandas")

scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
4    5  0.709663
7    8  0.698523
5    6  0.695438
6    7  0.692776
2    3  0.692301
8    9  0.691397
3    4  0.687542
9   10  0.684710
10  11  0.679353
11  12  0.669135
13  14  0.653043
12  13  0.652452
1    2  0.649537
14  15  0.641319
0    1  0.618293

In [85]:
# MinMax Scaler
scaler = MinMaxScaler().set_output(transform="pandas")

scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
5    6  0.686453
6    7  0.681397
4    5  0.678191
7    8  0.677849
8    9  0.674605
9   10  0.671331
2    3  0.661415
10  11  0.658691
3    4  0.654668
11  12  0.652885
12  13  0.636796
13  14  0.625914
14  15  0.611317
1    2  0.594986
0    1  0.565138